// Generates schema.json (source of truth, from CONTRACT section 3), Schema.gs (embedded copy,
// because Apps Script cannot read JSON files) and dist/HouseBible-all.gs (one paste-able file).
// Run: node apps-script/build.mjs
import { writeFileSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

// field syntax: name:type | name:enum(a|b|c) | name:ref(table). types: text num date bool json files
const SPEC = {
  rooms: 'name:text floor:text length_in:num width_in:num height_in:num flooring:text wall_color:text paint_notes:text outlets:text windows:text notes:text photos:files',
  assets: 'name:text kind:enum(system|appliance|fixture|other) room:ref(rooms) brand:text model:text serial:text install_date:text location:text fuel:text notes:text warranty_expires:date pro_only:bool photos:files docs:json',
  shutoffs: 'name:text type:enum(water|gas|electric|other) room:ref(rooms) location:text how_to:text photos:files',
  tasks: 'title:text category:enum(house|steam|yard|safety|pet|vehicle|health|other) subject:text rule:json start:date time:text why:text how:text safety:text pro_only:bool asset:ref(assets) room:ref(rooms) assignee:text calendar:bool active:bool source:enum(seed|user) seed_key:text',
  task_log: 'task:ref(tasks) date:date by:text note:text cost:num photos:files',
  consumables: 'name:text asset:ref(assets) room:ref(rooms) spec:text qty_on_hand:num interval_days:num last_replaced:date notes:text',
  documents: 'title:text kind:enum(manual|receipt|permit|inspection|closing|warranty|insurance|photo|other) file:text room:ref(rooms) asset:ref(assets) project:ref(projects) tags:text expires:date notes:text',
  contacts: 'name:text trade:text company:text phone:text email:text last_job:text last_job_date:date cost:num would_rehire:bool notes:text',
  steam_log: 'date:date time:text water_level:text pressure_psi:num event:enum(check|vent|blowdown|service|problem) notes:text photos:files',
  projects: 'name:text status:enum(idea|planned|active|done|dropped) priority:enum(Safety|Damage|Comfort|Cosmetic) pro:bool season:text budget:num deps:json room:ref(rooms) notes:text steps:json parts:json capital_improvement:bool',
  materials: 'project:ref(projects) item:text qty:num unit:text price_hd:num price_hf:num price_other:num have:bool',
  expenses: 'date:date item:text store:text amount:num category:text project:ref(projects) room:ref(rooms) receipt:ref(documents) capital_improvement:bool notes:text',
  tools: 'name:text category:text status:enum(own|want) brand:text model:text notes:text',
  utilities: 'date:date kind:enum(gas|oil|electric|water|other) amount:num usage:num unit:text notes:text',
  sensitive: 'label:text ciphertext:text iv:text hint:text',
  settings: 'key:text value:json',
};

function parseField(tok) {
  const [name, rest] = tok.split(':');
  let m;
  if ((m = rest.match(/^enum\((.+)\)$/))) return { name, type: 'text', enum: m[1].split('|') };
  if ((m = rest.match(/^ref\((.+)\)$/))) return { name, type: 'ref', ref: m[1] };
  return { name, type: rest };
}

const schema = {
  schemaVersion: 1,
  system: ['id', 'rev', 'updatedAt', 'updatedBy', 'deleted'],
  tables: Object.fromEntries(Object.entries(SPEC).map(([t, s]) => [t, { fields: s.split(/\s+/).map(parseField) }])),
};
for (const [t, def] of Object.entries(schema.tables)) {
  for (const f of def.fields) if (f.ref && !schema.tables[f.ref]) throw new Error(`${t}.${f.name} refs unknown table ${f.ref}`);
}

writeFileSync(join(here, 'schema.json'), JSON.stringify(schema, null, 2) + '\n');
writeFileSync(join(here, 'Schema.gs'),
  '/* GENERATED from schema.json by apps-script/build.mjs. Do not edit by hand. */\n' +
  'var HB_SCHEMA = ' + JSON.stringify(schema, null, 2) + ';\n');

// one-file bundle for pasting into the Apps Script editor
const ORDER = ['Schema.gs', 'Logic.gs', 'Store.gs', 'Files.gs', 'Calendar.gs', 'Weather.gs', 'Api.gs', 'Setup.gs'];
let bundle = '/* House Bible backend, single-file bundle generated by apps-script/build.mjs. */\n';
for (const f of ORDER) {
  try { bundle += `\n/* ===== ${f} ===== */\n` + readFileSync(join(here, f), 'utf8'); } catch { /* not written yet */ }
}
writeFileSync(join(here, 'dist', 'HouseBible-all.gs'), bundle);
console.log('built schema.json, Schema.gs, dist/HouseBible-all.gs');
